In [20]:
import numpy as np

In [7]:
a = np.array([10,20,30,40,50])
print(a)

[10 20 30 40 50]


In [6]:
arrfloat = np.array([10.0,20.0,30.0,40.0,50.0])
print(arrfloat)

[10. 20. 30. 40. 50.]


In [9]:
matfloat = np.array([[10.0,20.0,30.0],[40.0,50.0,60.0]])
print(matfloat)

[[10. 20. 30.]
 [40. 50. 60.]]


In [10]:
aaa = np.array([[[1,2,3],[4,5,6], [7,8,9]],[[10,11,12],[13,14,15],[16,17,18]]])
print(aaa)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]]


In [11]:
aaa.shape

(2, 3, 3)

In [13]:
aaa.size

18

In [16]:
aaaa = np.array([[[[1,2,3],[4,5,6], [7,8,9]],[[10,11,12],[13,14,15],[16,17,18]]],[[[19,20,21],[22,23,24],[25,26,27]],[[28,29,30],[31,32,33],[34,35,36]]]])
print(aaaa)

[[[[ 1  2  3]
   [ 4  5  6]
   [ 7  8  9]]

  [[10 11 12]
   [13 14 15]
   [16 17 18]]]


 [[[19 20 21]
   [22 23 24]
   [25 26 27]]

  [[28 29 30]
   [31 32 33]
   [34 35 36]]]]


In [17]:
aaaa.shape

(2, 2, 3, 3)

In [18]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [19]:
print(np.zeros((2,4)))

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [20]:
print(np.zeros((2,5,3)))

[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]


In [23]:
print(np.zeros((2,3,4,5)))

[[[[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]]


 [[[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]]]


In [27]:
qu = np.ones((5,5), dtype=int)
print(qu)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [28]:
t = np.array([1,2,3,4,5,6,7,8,9], dtype=int)
print(t)

[1 2 3 4 5 6 7 8 9]


In [29]:
print(t[1:-1])

[2 3 4 5 6 7 8]


In [33]:
qt = np.arange(1,31)
qt = qt.reshape(6,5)
print(qt)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]]


In [37]:
qt[2:4, :2]

array([[11, 12],
       [16, 17]])

In [41]:
a = range(1, 30, 6)
for x in a: 
    print(x)

1
7
13
19
25


In [2]:
np.full((4,3), 2)

array([[2, 2, 2],
       [2, 2, 2],
       [2, 2, 2],
       [2, 2, 2]])

In [15]:
a = np.arange(1,100)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [19]:
b = np.linspace(1, 100)
b

array([  1.        ,   3.02040816,   5.04081633,   7.06122449,
         9.08163265,  11.10204082,  13.12244898,  15.14285714,
        17.16326531,  19.18367347,  21.20408163,  23.2244898 ,
        25.24489796,  27.26530612,  29.28571429,  31.30612245,
        33.32653061,  35.34693878,  37.36734694,  39.3877551 ,
        41.40816327,  43.42857143,  45.44897959,  47.46938776,
        49.48979592,  51.51020408,  53.53061224,  55.55102041,
        57.57142857,  59.59183673,  61.6122449 ,  63.63265306,
        65.65306122,  67.67346939,  69.69387755,  71.71428571,
        73.73469388,  75.75510204,  77.7755102 ,  79.79591837,
        81.81632653,  83.83673469,  85.85714286,  87.87755102,
        89.89795918,  91.91836735,  93.93877551,  95.95918367,
        97.97959184, 100.        ])

In [21]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [22]:
id = np.identity(4)
id

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [23]:
sp = np.full((4,4), 6)
sp

array([[6, 6, 6, 6],
       [6, 6, 6, 6],
       [6, 6, 6, 6],
       [6, 6, 6, 6]])

In [24]:
np.multiply(id, sp)

array([[6., 0., 0., 0.],
       [0., 6., 0., 0.],
       [0., 0., 6., 0.],
       [0., 0., 0., 6.]])

In [25]:
id*sp

array([[6., 0., 0., 0.],
       [0., 6., 0., 0.],
       [0., 0., 6., 0.],
       [0., 0., 0., 6.]])

In [26]:
np.matmul(id, sp)

array([[6., 6., 6., 6.],
       [6., 6., 6., 6.],
       [6., 6., 6., 6.],
       [6., 6., 6., 6.]])